# Generated by Django 5.2.3 on 2025-06-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='beneficios_favoritos',
            new_name='beneficios',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='beneficio',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='categoriabeneficio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriabeneficio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
